### ISSUE TITLE
Calculating incorrectly?

### ISSUE THREAD

**Issue by custa1200** [sakamies/postcss-gridlover#3]
``` css
html {
  --base-font-size: 1rem;
  --base-line-height: 1.5;
  --base-scale-factor: 1.618;
  --base-units: rem;
}

body {
  padding: 0;
  margin: 0;
  font-size: 0sx;
  line-height: 0gr;
}
```

Outputs as:

``` css
html {
  --base-font-size: 16px;
  --base-font-size: 1rem;
  --base-line-height: 1.5;
  --base-scale-factor: 1.618;
  --base-units: rem;
}
body {
  padding: 0;
  margin: 0;
  font-size: 16px;
  font-size: 1rem;
  line-height: 32px;
  line-height: 2rem;
}
```

But it should only be line height 24px and 1.5rem?
