### ISSUE TITLE
Unable to use non integer Grid units

### ISSUE THREAD

**Issue by custa1200** [sakamies/postcss-gridlover#6]
I am unable to use non integer grid units. i.e. 
```css
html {
--base-font-size: 16px;
--base-line-height: 1.5;
--base-scale-factor: 1.618;
--base-units: rem;
font-size: var(--base-font-size);
line-height: var(--base-line-height);
}

.foo {
  font-size: 0sx;
  line-height: 0.5gr;
  width: ((1gr)*5);
  height: 2gr;
  border: 1.5gr;
}
```
produces...
```css
html {
  --base-font-size: 16px;
  --base-line-height: 1.5;
  --base-scale-factor: 1.618;
  --base-units: rem;
  font-size: var(--base-font-size);
  line-height: var(--base-line-height);
}

.foo {
  font-size: 1rem;
  line-height: 1.5rem;
  width: 7.5rem;
  height: 3rem;
  border: 1.7.5rem;
}
```
Notice the line-height and the border.
