### ISSUE TITLE
vertical grid

### ISSUE THREAD

**Issue by eduarddotgg** [sakamies/postcss-gridlover#7]
It would be nice to generate vertical grid, so there was visual representation of grid for development.

What do you think?

**Comment by sakamies** [comment]
You can do a vertical grid with a bit of css. I should probably add this to the examples.

```css
body {
  background-image: linear-gradient(currentColor 1px, transparent 1px);
  background-size: 1gr 1gr;
  background-position: 0% 0%;
  background-repeat: repeat;
}
```
